const skills=["Meta Ads Manager","Lead Generation","Audience Targeting","Retargeting","A/B Testing","Campaign Optimization","CTR / CPL Analysis","Performance Reporting"];
export default function Home(){return <main>
<nav className="nav"><div className="brand">GY<span>.</span></div><div className="links"><a href="#work">Work</a><a href="#skills">Skills</a><a href="#about">About</a><a href="#contact">Contact</a></div></nav>
<section className="hero"><div className="eyebrow">META ADS • PERFORMANCE MARKETING</div><h1>Gaurav<br/><em>Yadav.</em></h1><p className="lead">Meta Ads focused digital marketing professional building targeted campaigns, generating leads and continuously optimizing performance.</p><div className="actions"><a className="btn primary" href="#work">Explore my work ↗</a><a className="btn ghost" href="#contact">Let&apos;s connect</a></div><div className="hero-note">Open to Meta Ads / Performance Marketing opportunities</div></section>
<section id="about" className="section split"><div><div className="eyebrow">01 / ABOUT</div><h2>Focused on paid social that has a purpose.</h2></div><div className="copy"><p>I&apos;m Gaurav Yadav, a digital marketing professional with a background in IT and office operations, with hands-on focus on Meta advertising.</p><p>My approach is practical: understand the audience, build the campaign, test creatives and targeting, monitor the right metrics and optimize based on data.</p><div className="facts"><div><strong>Master&apos;s</strong><span>IT</span></div><div><strong>PGDCA</strong><span>Computer Applications</span></div><div><strong>3–5 yrs</strong><span>Office experience</span></div></div></div></section>
<section id="skills" className="section"><div className="eyebrow">02 / EXPERTISE</div><h2>Meta Ads toolkit</h2><div className="grid">{skills.map((s,i)=><div className="card" key={s}><span>0{i+1}</span><h3>{s}</h3><p>Practical campaign-focused capability.</p></div>)}</div></section>
<section id="work" className="section work"><div className="eyebrow">03 / SELECTED WORK</div><h2>Campaign experience</h2><div className="case"><div className="case-tag">CASE STUDY / 01</div><h3>Visa Now Immigration</h3><p>Meta Ads and social media campaign work for an immigration-focused business. Campaign details, creatives and verified performance metrics will be added here.</p><div className="case-grid"><div><small>OBJECTIVE</small><strong>Lead Generation</strong></div><div><small>CHANNEL</small><strong>Facebook + Instagram</strong></div><div><small>STATUS</small><strong>Details to be updated</strong></div></div></div></section>
<section className="section process"><div className="eyebrow">04 / PROCESS</div><h2>How I approach a campaign.</h2><div className="steps">{["Research","Setup","Launch","Test","Optimize","Report"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></section>
<section id="contact" className="contact"><div className="eyebrow">05 / CONTACT</div><h2>Have a role or project<br/><em>in mind?</em></h2><p>Let&apos;s connect and discuss how I can contribute to your marketing team.</p><a className="btn primary" href="mailto:YOUR_EMAIL@example.com">YOUR_EMAIL@example.com ↗</a><div className="footer">© 2026 Gaurav Yadav · Meta Ads Specialist</div></section>
</main>}