const skills=["Meta Ads Manager","Lead Generation","Audience Targeting","Retargeting","A/B Testing","Campaign Optimization","CTR / CPL Analysis","Performance Reporting"];
const stages=[["01","AUDIENCE","Research"],["02","AD","Creative + Offer"],["03","CLICK","Landing / CTA"],["04","LEAD","Conversion"],["05","OPTIMIZE","Data feedback"]];
export default function Home(){return <main>
<nav className="nav"><a className="brand" href="#top">GY<span>.</span></a><div className="links"><a href="#work">Work</a><a href="#expertise">Expertise</a><a href="#process">Process</a><a href="#about">About</a></div><a className="nav-cta" href="#contact">Let&apos;s talk ↗</a></nav>
<section id="top" className="hero"><div className="hero-copy"><div className="eyebrow reveal">META ADS / PERFORMANCE MARKETING</div><h1 className="reveal delay-1">Turn attention<br/><em>into action.</em></h1><p className="lead reveal delay-2">Meta Ads focused digital marketing professional building targeted campaigns, generating leads and optimizing performance through data.</p><div className="actions reveal delay-3"><a className="btn primary" href="#work">Explore my work ↗</a><a className="btn ghost" href="#contact">Let&apos;s connect</a></div><div className="hero-note">OPEN TO META ADS / PERFORMANCE MARKETING OPPORTUNITIES</div></div><div className="dashboard-wrap float"><div className="dashboard"><div className="dash-head"><span>CAMPAIGN OVERVIEW</span><i>LIVE</i></div><h3>Visa Now Immigration</h3><div className="dash-stats">{[["Leads","—"],["CPL","—"],["CTR","—"],["ROAS","—"]].map(([a,b])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="chart"><div className="chart-top"><span>PERFORMANCE TREND</span><span>VERIFIED DATA</span></div><div className="bars">{[35,48,42,68,55,82,72,92].map((h,i)=><b key={i} style={{height:h+"%"}}/>)}</div></div><div className="dash-foot">Metrics will be added from verified campaign data.</div></div><div className="orb orb-a"/><div className="orb orb-b"/></div></section>
<section className="ticker"><span>META ADS</span><b>•</b><span>LEAD GENERATION</span><b>•</b><span>AUDIENCE TARGETING</span><b>•</b><span>RETARGETING</span><b>•</b><span>A/B TESTING</span><b>•</b><span>OPTIMIZATION</span></section>
<section id="expertise" className="section expertise"><div className="section-head"><div className="eyebrow">01 / WHAT I DO</div><h2>Performance marketing<br/>with a clear objective.</h2></div><div className="expertise-grid">{[["01","Campaign setup","Objectives, structure, placements and tracking."],["02","Audience","Targeting, segmentation and retargeting."],["03","Creative testing","Test hooks, formats and messaging."],["04","Optimization","Monitor CTR, CPL and campaign signals."]].map(([n,t,d])=><article className="service-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><i>↗</i></article>)}</div></section>
<section id="process" className="section engine"><div className="eyebrow">02 / CAMPAIGN ENGINE</div><h2>From audience<br/>to lead.</h2><div className="funnel">{stages.map(([n,t,d],i)=><div className={"stage "+(i===4?"active":"")} key={n}><span>{n}</span><strong>{t}</strong><small>{d}</small>{i<4&&<b className="arrow">→</b>}</div>)}</div></section>
<section id="work" className="section case-section"><div className="eyebrow">03 / SELECTED WORK</div><h2>Visa Now Immigration</h2><p className="case-sub">Meta Ads / Lead Generation / Facebook + Instagram</p><div className="case-layout"><div className="case-visual"><div className="visual-label">CAMPAIGN VISUAL</div><div className="mock-chart"><div className="mock-line"/><div className="mock-bars">{[32,45,28,58,52,76,62].map((h,i)=><span key={i} style={{height:h+"%"}}/>)}</div></div><div className="mock-pills"><span>Audience</span><span>Creative</span><span>Optimization</span></div></div><div className="case-info">{[["OBJECTIVE","Lead Generation"],["CHANNEL","Facebook + Instagram"],["ROLE","Meta Ads / Campaign Work"],["RESULTS","Verified metrics to be added"]].map(([a,b])=><div className="info-row" key={a}><small>{a}</small><strong>{b}</strong></div>)}<p>Campaign screenshots, creatives and verified performance data can be added here to turn this into a complete recruiter-ready case study.</p></div></div></section>
<section id="about" className="section about"><div><div className="eyebrow">04 / ABOUT</div><h2>IT background.<br/><em>Paid social focus.</em></h2></div><div className="about-copy"><p>I&apos;m Gaurav Yadav — a digital marketing professional with a Master&apos;s in IT and PGDCA, with hands-on focus on Meta advertising.</p><p>My approach is practical: understand the audience, build the campaign, test creatives and targeting, monitor the right metrics and optimize based on data.</p><div className="facts"><div><strong>Master&apos;s</strong><span>IT</span></div><div><strong>PGDCA</strong><span>Computer Applications</span></div><div><strong>3–5 yrs</strong><span>Office experience</span></div></div></div></section>
<section className="section skills"><div className="eyebrow">05 / EXPERTISE STACK</div><h2>Meta Ads toolkit.</h2><div className="skill-grid">{skills.map((s,i)=><div className="skill" key={s}><span>0{i+1}</span><strong>{s}</strong><i>↗</i></div>)}</div></section>
<section id="contact" className="contact"><div className="eyebrow">06 / LET&apos;S CONNECT</div><div className="contact-grid"><div><h2>Have a role or<br/><em>project in mind?</em></h2><p>Let&apos;s connect and discuss how I can contribute to your marketing team.</p></div><div className="contact-card"><span>AVAILABLE FOR</span><strong>Meta Ads / Performance Marketing</strong><a href="mailto:gaurav204yadav@gmail.com">gaurav204yadav@gmail.com ↗</a><a href="tel:+918360992034">+91 83609 92034</a></div></div><footer><span>GY. / META ADS</span><span>© 2026 Gaurav Yadav</span></footer></section>
</main>}